src/evaluaciones/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

src/presentations/urls.py
from django.urls import path

from .views import evaluation_form_page, update_context_view, upload_grade

app_name = 'presentations'
urlpatterns = [
    path('evaluar/<int:evaluation_id>/<int:group_id>', evaluation_form_page, name='form'),
    path('evaluar/<int:evaluation_id>/<int:group_id>/subir_nota', upload_grade, name='upload_grade'),
    path('evaluar/<int:evaluation_id>/<int:group_id>/update_context', update_context_view, name='ajax_update'),
]

src/project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views

from users.views import landing_page, evaluators_page, registro_usuario
from courses.views import courses_page
from evaluations.views import evaluations_page
from rubrics.views import rubrics_page

urlpatterns = [
    path('', landing_page, name="Landing Page"),
    path('cursos/', courses_page, name="Courses Page"),
    #path('evaluadores/', evaluators_page, name="Evaluators Page"),
    path('evaluadores/', registro_usuario.as_view(), name="Evaluators Page"),
    path('evaluadores/', include('users.urls'), name="Edit Users"),
    path('rubricas/', rubrics_page, name="Rubrics Page"),
    path('rubricas/', include('rubrics.urls'), name="Rubrics Editor"),
    path('evaluaciones/', evaluations_page, name="Evaluations Page"),
    path('evaluaciones/', include('presentations.urls'), name="Evaluation Form"),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('admin/', admin.site.urls),
]

src/users/urls.py
from django.urls import path
from .views import registro_usuario, DeleteUserView, EditUserView

from . import views

app_name = 'users'
urlpatterns = [
    path('<int:pk>', EditUserView.as_view(), name='edit'),
    path('<int:pk>/delete', DeleteUserView.as_view(), name='delete')
]

src/evaluations/models.py
from django.db import models

# Create your models here.

class Evaluation(models.Model):

    rubric = models.ForeignKey("rubrics.Rubric", null=True, on_delete=models.SET_NULL)
    course = models.ForeignKey("courses.Course", null=False, on_delete=models.CASCADE)
    default_allowed_evaluators = models.ManyToManyField("users.BaseUser")
    is_open = models.BooleanField(default=True)

src/presentations/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.

class Presentation(models.Model):
    
    evaluation = models.ForeignKey("evaluations.Evaluation", on_delete=models.CASCADE)
    group = models.ForeignKey("courses.Group",on_delete=models.CASCADE)
    allowed_evaluators = models.ManyToManyField("users.BaseUser")
    presentators = models.ManyToManyField("courses.Student")

    def __str__(self):
        return str(self.evaluation.course) + "-eval" + str(self.evaluation.id) + "-group" + str(self.group.number)

    class Meta:
        unique_together = (("evaluation", "group"),)

class Grade(models.Model):   
    evaluator = models.ForeignKey("users.BaseUser", on_delete=models.CASCADE)
    presentation = models.ForeignKey("presentations.Presentation", on_delete=models.CASCADE)
    student = models.ForeignKey("courses.Student", on_delete=models.CASCADE)
    value = models.TextField(default="")
    state = models.BooleanField(default=False)

    class Meta:
        unique_together = (("evaluator", "presentation", "student"),)

src/evaluations/forms.py
from django import forms
from .models import Evaluation

class EvaluationsForm(forms.ModelForm):

    class Meta:
        model = Evaluation
        fields = [
            "course",
            "rubric"
        ]        

src/presentations/forms.py
from django import forms
import pandas as pd

from .models import Presentation

class EvaluationDurationForm(forms.Form):
  duracion = forms.DecimalField(max_digits=3, widget=forms.NumberInput(attrs={
                        'class' : "w3-input w3-border w3-round",
                        'size'  : "1",
                        'style' : "width:20%; display:inline; margin-left: 5%",
                        'id'  : 'duration-input',
                        'required' : 'true'
    }))

class EvaluationCriterionForm(forms.Form):
    '''
    Forma para elegir los niveles de logro de una rúbrica. Cada fila es una selección, donde se
    elige el niveltext = forms.CharField(max_length=50, widget=forms.Textarea())
  col = forms.IntegerField()
  row = forms.IntegerField() de logro.
    '''
    def __init__(self, *args, **kwargs):
        tabla_df = kwargs.pop('table') # Obtener la tabla

        super(EvaluationCriterionForm, self).__init__(*args, **kwargs)

        puntajes = tabla_df.columns.values[1:]
        for rowindex, crit in tabla_df.iterrows():
            # Crear un campo de elección para cada fila de la rubrica
           fieldname = crit[0] # Primera columna es el nombre del criterio
           choices = []
           for index, nlogro in  enumerate(crit[1:]):
               choices.append((puntajes[index], nlogro)) # (puntaje, name)
           self.fields[fieldname] = forms.ChoiceField(label=fieldname, choices = choices,
                                                     widget=CriterionWidg)
           self.fields[fieldname].widget.attrs.update({'label' : fieldname})

class CriterionWidg(forms.RadioSelect):
    '''
    Widget para mostrar un criterio y sus niveles de logro
    '''
    template_name = 'criterions/select_criterion.html'
    option_template_name = 'criterions/select_criterion_option.html'

class EvaluatorsListForm(forms.ModelForm):

    class Meta:
        model = Presentation
        fields = ["allowed_evaluators"]

class PresentatorsListForm(forms.ModelForm):

    class Meta:
        model = Presentation
        fields = ["presentators"]

src/evaluations/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpRequest
from presentations.models import Grade
from .models import Evaluation
from courses.models import Course
from rubrics.models import Rubric
from presentations.models import Presentation
from django.db.models.query import QuerySet
from .forms import EvaluationsForm

from django.views import View

# Create your views here.


def evaluations_page(request: HttpRequest, *args):
    
    if request.user.is_staff:
        evaluaciones=  Evaluation.objects.all()
        if(request.method == "POST"):
            form = EvaluationsForm(request.POST)
            if form.is_valid():
                post = form.save(commit=True)
                post.save()
                course: Course = Evaluation.objects.get(id=post.id).course
                for group in course.group_set.all():
                    Presentation.objects.create(evaluation=Evaluation.objects.get(id=post.id), group=group)
            
        else:
            form = EvaluationsForm()
        return render(request, "evaluations.html",{'evaluaciones': evaluaciones, 'form' : form})
    else:
        userid = request.user.id  
        grades = Grade.objects.filter(evaluator_id = userid)[:10] #All grades for the evaluator     
        context = {
            'obj' : grades
        }
        return render(request, "evaluations.html", context)

src/presentations/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse, HttpRequest

from .models import Presentation, Grade
from .forms import EvaluationCriterionForm, EvaluationDurationForm, EvaluatorsListForm, PresentatorsListForm

import pandas as pd

# Create your views here.

def evaluation_form_page(request: HttpRequest, evaluation_id: int, group_id: int, *args):
    presentation: Presentation = get_object_or_404(Presentation, evaluation_id=evaluation_id, group_id=group_id)

    presentators = presentation.presentators.all()

    evaluation: Evaluation = presentation.evaluation

    all_evaluations = evaluation.course.evaluation_set.all()
    all_presentations = []

    for other_evaluation in all_evaluations:
        for other_presentation in other_evaluation.presentation_set.all():
            all_presentations.append(other_presentation)

    allowed_evaluators_set = presentation.allowed_evaluators.all()

    group_members = presentation.group.student_set.all()

    grades = presentation.grade_set.all()

    all_grades = Grade.objects.filter(presentation__evaluation__course=evaluation.course)

    # Constructs the allowed evaluators' info, including their evaluation status
    allowed_evaluators = []

    for evaluator in allowed_evaluators_set:

        evaluator_answered_grades = 0
        evaluator_total_grades = 0

        for presentator in presentators:

            evaluator_answered_grades += grades.filter(state=True, evaluator=evaluator, presentation=presentation, student=presentator).count()

            evaluator_total_grades += grades.filter(evaluator=evaluator, presentation=presentation, student=presentator).count()

        evaluator_expected_grades = presentators.all().count()

        if evaluator_total_grades != evaluator_expected_grades:
            evaluator_status = "pending"
        elif evaluator_answered_grades != evaluator_expected_grades:
            evaluator_status = "evaluating"
        else:
            evaluator_status = "done"

        allowed_evaluators.append((evaluator.username, evaluator_status))

    # Constructs the group members' info, including their presentation statuses
    group_member_statuses = []

    for group_member in group_members:
        
        group_member_status = "pending"

        for other_presentation in all_presentations:
            if ((other_presentation.presentators.filter(name=group_member.name, rut=group_member.rut).count() != 0) and 
                (all_grades.filter(presentation=other_presentation, student=group_member, state=True).count() == other_presentation.allowed_evaluators.all().count())):
                group_member_status = "done"
                break

        group_member_statuses.append((group_member.name, group_member_status))

    current_presentators = []

    for presentator in presentators:

        current_presentators.append(presentator.name)

    
    # Obtener la tabla asociada a la rubrica, y sus datos
    rubrica = evaluation.rubric
    rubrica_df = rubrica.to_df()
    dmin = rubrica.duration_min
    dmax = rubrica.duration_max

    # forma para los criterios
    criterion_form = EvaluationCriterionForm(table=rubrica_df)

    # forma para el tiempo
    duration_form = EvaluationDurationForm()

    edit_evaluators_form = EvaluatorsListForm(request.POST or None, instance=presentation)
    edit_presentators_form = PresentatorsListForm(request.POST or None, instance=presentation)
    
    if request.method == "POST":
        if edit_evaluators_form.is_valid():
            edit_evaluators_form.save()
        if edit_presentators_form.is_valid():
            edit_presentators_form.save()

        return redirect("presentations:form", evaluation_id=evaluation_id, group_id=group_id)

    context = {
        "evaluation_status": evaluation.is_open,
        "group_name": presentation.group.name,
        "group_id" : presentation.group.id,
        "presentation_number": evaluation.id,
        "course": str(evaluation.course),
        "allowed_evaluators": allowed_evaluators,
        "group_members": group_member_statuses,
        "current_presentators": current_presentators,
        "criterion_form" : criterion_form,
        "duration_min" : dmin,
        "duration_max" : dmax,
        "duration_form" : duration_form,
        "edit_evaluators_form": edit_evaluators_form,
        "edit_presentators_form": edit_presentators_form,
    }

    return render(request, "evaluation_form.html", context);

def upload_grade(request, evaluation_id, group_id):
    if not request.POST:
        return redirect('presentations:form', evaluation_id=evaluation_id, group_id=group_id)

    presentation: Presentation = get_object_or_404(Presentation, evaluation_id=evaluation_id, group_id=group_id)

    presentators = presentation.presentators.all()
    evaluation: Evaluation = presentation.evaluation

    # Obtener la tabla asociada a la rubrica, y sus datos
    rubrica = evaluation.rubric
    rubrica_df = rubrica.to_df()
    dmin = rubrica.duration_min
    dmax = rubrica.duration_max

    # Obtener los presentadores


    # forma para los criteriosevaluator
    criterion_form = EvaluationCriterionForm(request.POST, table=rubrica_df)
    if criterion_form.is_valid():
        puntaje_dict = criterion_form.cleaned_data

        puntajes_df = pd.DataFrame.from_dict(puntaje_dict, orient='index')

        for student in presentators:
            grade = Grade(evaluator=request.user, student=student,
                presentation=presentation, value=puntajes_df.to_csv(), state=True)
            grade.save()
        return redirect('Evaluations Page')




def update_context_view(request: HttpRequest, evaluation_id: int, group_id: int):
    
    context = {}

    if request.method == "POST":

        presentation: Presentation = get_object_or_404(Presentation, evaluation_id=evaluation_id, group_id=group_id)

        allowed_evaluators_set = presentation.allowed_evaluators.all()

        presentators = presentation.presentators.all()

        grades = presentation.grade_set.all()

        # Constructs the allowed evaluators' info, including their evaluation status
        allowed_evaluators = []

        for evaluator in allowed_evaluators_set:

            evaluator_answered_grades = 0
            evaluator_total_grades = 0

            for presentator in presentators:

                evaluator_answered_grades += grades.filter(state=True, evaluator=evaluator, presentation=presentation, student=presentator).count()

                evaluator_total_grades += grades.filter(evaluator=evaluator, presentation=presentation, student=presentator).count()

            evaluator_expected_grades = presentators.all().count()

            if evaluator_total_grades != evaluator_expected_grades:
                evaluator_status = "pending"
            elif evaluator_answered_grades != evaluator_expected_grades:
                evaluator_status = "evaluating"
            else:
                evaluator_status = "done"

            allowed_evaluators.append((evaluator.username, evaluator_status))

        context["allowed_evaluators"] = allowed_evaluators

        group_members = presentation.group.student_set.all()

        evaluation: Evaluation = presentation.evaluation

        context["evaluation_status"] = evaluation.is_open

        all_evaluations = evaluation.course.evaluation_set.all()
        all_presentations = []

        for other_evaluation in all_evaluations:
            for other_presentation in other_evaluation.presentation_set.all():
                all_presentations.append(other_presentation)

        all_grades = Grade.objects.filter(presentation__evaluation__course=evaluation.course)

        # Constructs the group members' info, including their presentation statuses
        group_member_statuses = []

        for group_member in group_members:
            
            group_member_status = "pending"

            for other_presentation in all_presentations:
                if ((other_presentation.presentators.filter(name=group_member.name, rut=group_member.rut).count() != 0) and 
                    (all_grades.filter(presentation=other_presentation, student=group_member, state=True).count() == other_presentation.allowed_evaluators.all().count())):
                    group_member_status = "done"
                    break

            group_member_statuses.append((group_member.name, group_member_status))

        context["group_members"] = group_member_statuses

        current_presentators = []

        for presentator in presentators:

            current_presentators.append(presentator.name)

        context["current_presentators"] = current_presentators

    return JsonResponse(context)

src/presentations/templates/duration_sect.html
<div class="w3-panel w3-margin-bottom w3-card-4 w3-padding-16 w3-twothird w3-right" style="margin-right: 1.8%">
	{% if user.is_staff %}
	<div style="margin-left:21%"><i class="far fa-clock"></i>Duración esperada (min):
	  <span id="duration-min" style="width:20%; display:inline; margin-left: 5%"> {{duration_min}} </span> - 
	  <span id="duration-max" style="width:20%; display:inline;"> {{duration_max}} </span>
	</div>
	{% endif %}
  <div style="margin-left:21%"><i class="far fa-clock"></i> Duración de la presentación (min): {{duration_form.duracion}}{{duration_form.errors}}
</div>
<div> <b id="discount-warning" style="color: red;"></b> </div>
</div>

src/presentations/templates/evaluation_form.html
{% extends 'base.html' %}

{% load static %}

{% block title %}

<title>
  Sistema de Evaluación
</title>

{% endblock title %}

{% block stylesheets %}

<!-- Evaluation Form CSS -->
<link rel="stylesheet" type="text/css" href="{% static 'presentations/presentations.css' %}">

{% endblock stylesheets %}

{% block javascript %}

<!-- Evaluation Form JS -->
<script type="text/javascript" src="{% static 'presentations/presentations.js' %}"></script>

{% endblock javascript %}

{% block content %}

<!-- Photo grid (modal) -->

<!-- Portada -->
<div class="w3-container" id="portada" style="margin-top:80px; margin-bottom:10px">
  <h1 class="w3-xxxlarge w3-text-red">
    <b>
      Evaluación
      <span id="status_message" class="{% if evaluation_status %} done {% else %} pending {% endif %}">
        {% if evaluation_status %}
          <i class="w3-text-green">
            en curso
          </i>
        {% else %}
          <i class="w3-text-red">
            cerrada
          </i>    
        {% endif %}
      </span>
    </b>
  </h1>
  <hr style="width:50px;border:5px solid red" class="w3-round">
</div>

<!-- Evaluacion -->
<div class="w3-container w3-center">
  <p><b>{{ group_name }}</b> Presentación {{ presentation_number }} <i>{{ course }}</i></p>
  <br>
</div>

<div class="w3-panel  w3-margin-bottom">
  <ul id="evaluators_list" class="w3-ul w3-light-grey w3-center w3-card-4">
    <li class="w3-dark-grey w3-xlarge w3-padding-32">Evaluadores <i class="fas fa-user-tie"></i> </li>
    {% for evaluator, status in allowed_evaluators %}
      <li id="{{ evaluator }}" class="evaluator_item w3-padding-16">
        <span class="evaluator_name">
          {{ evaluator }}
        </span>
        <span class="evaluator_status {{status}}">
          {% if status == "done" %}
            <i style="margin-left: 10px" class="presentado far fa-check-circle"></i>
            <i class="presentado w3-small">
              ya evaluó
            </i>
          {% elif status == "evaluating" %}
            <i style="margin-left: 10px" class="fa fa-spinner fa-lg fa-spin"></i>
            <i class="w3-small">
              evaluando
            </i>
          {% else %}
            <i style="margin-left: 10px" class="w3-large fas fa-times"></i>
            <i class="w3-small">
              aún no evalúa
            </i>
          {% endif %}
        </span>
      </li>
    {% endfor %}
    {% if user.is_staff %}
      <li class="add_evaluator_trigger w3-padding-16"> Editar Lista <i style="margin-left: 10px" class="fas fa-pen"></i>
      </li>
    {% endif %}
  </ul>
</div>

{% if user.is_staff %}

<!-- The Modal -->
<div id="add_evaluator_modal" class="w3-modal">
  <div class="w3-modal-content">
    <div class="w3-container">
      <span onclick='$("#add_evaluator_modal").hide();'
      class="w3-button w3-display-topright">&times;</span>
      <form method="POST">
        {% csrf_token %}
        {{ edit_evaluators_form }}
        <button class="w3-button w3-xlarge w3-red w3-display-bottomright">
          Aceptar
        </button>
      </form>
    </div>
  </div>
</div> 

{% endif %}

<div class="w3-row-padding" style="margin-top:30px">
  <div class="w3-half w3-margin-bottom ">
    <ul id="group_member_list" class="w3-ul w3-light-grey w3-center w3-card-4">
      <li class="w3-dark-grey w3-xlarge w3-padding-32">Miembros del equipo <i class="fas fa-user-friends"></i></li>
      {% for student, status in group_members %}
        <li class="group_member_item w3-padding-16">
          <span class="group_member_name">
            {{ student }}
          </span>
          {% if status == "done" %}
            <span class="group_member_status {{status}}">
              <i class="presentado far fa-check-circle"></i>
              <i class="presentado w3-small">
                ya presentó
              </i>
            </span>
          {% endif %}
        </li>
      {% endfor %}
    </ul>
  </div>

  <div class="w3-half w3-margin-bottom ">
    <ul id="presentators_list" class="w3-ul w3-light-grey w3-center w3-card-4">
      <li class="w3-dark-grey w3-xlarge w3-padding-32">Miembros que presentan <i class="fas fa-chalkboard-teacher"></i></li>
      {% for presentator in current_presentators %}
        <li class="presentator_item w3-padding-16">
          <span class="presentator_name">
            {{ presentator }}
          </span>
          <i style="margin-left: 10px" class="w3-large fas fa-times"></i>
        </li>
      {% endfor %}

      {% if user.is_staff %}
        <li class="add_presentator_trigger w3-padding-16" id="mas"> 
          Editar Lista
          <i style="margin-left: 10px" class="fas fa-pen"></i>
        </li>
      {% endif %}

    </ul>
  </div>
</div>

{% if user.is_staff %}

<!-- The Modal -->
<div id="add_presentator_modal" class="w3-modal">
  <div class="w3-modal-content">
    <div class="w3-container">
      <span onclick='$("#add_presentator_modal").hide();'
      class="w3-button w3-display-topright">&times;</span>
      <form method="POST">
        {% csrf_token %}
        {{ edit_presentators_form }}
        <button class="w3-button w3-xlarge w3-red w3-display-bottomright">
          Aceptar
        </button>
      </form>
    </div>
  </div>
</div> 

{% endif %}

<form action="{% url 'presentations:upload_grade' evaluation_id=presentation_number group_id=group_id %}" method="POST">
{% csrf_token %}

<div class="w3-container w3-center">
  <p>Seleccione el nivel de logro alcanzado por el grupo en cada ámbito</p>

{% include "criterions/criterions.html" %}
{% if user.is_staff %}
  {% include "duration_sect.html" %}
{% endif %}
<div class="w3-panel w3-right w3-half">
  <button class="w3-button w3-xlarge w3-red" style="margin-left: 15%"> <i class="fas fa-envelope-open-text"></i> Entregar evaluación</button>
</div>
</div>
</form>

{% endblock content %}