src/evaluaciones/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

src/project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views

from users.views import landing_page, evaluators_page, registro_usuario
from courses.views import courses_page
from evaluations.views import evaluations_page
from rubrics.views import rubrics_page

urlpatterns = [
    path('', landing_page, name="Landing Page"),
    path('cursos/', courses_page, name="Courses Page"),
    #path('evaluadores/', evaluators_page, name="Evaluators Page"),
    path('evaluadores/', registro_usuario.as_view(), name="Evaluators Page"),
    path('evaluadores/', include('users.urls'), name="Edit Users"),
    path('rubricas/', rubrics_page, name="Rubrics Page"),
    path('rubricas/', include('rubrics.urls'), name="Rubrics Editor"),
    path('evaluaciones/', evaluations_page, name="Evaluations Page"),
    path('evaluaciones/', include('presentations.urls'), name="Evaluation Form"),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('admin/', admin.site.urls),
]

src/rubrics/urls.py
from django.urls import path
from .views import RubricView, newRubricView, DeleteRubricView, RubricCopyView

from . import views

app_name = 'rubrics'
urlpatterns = [
    path('new', newRubricView, name='new'),
    path('<int:rubric_id>', RubricView.as_view(), name='view'),
    path('<int:pk>/delete', DeleteRubricView.as_view(), name='delete'),
    path('<int:rubric_id>/<int:eval_id>/copy', RubricCopyView.as_view(), name='copy')
]

src/users/urls.py
from django.urls import path
from .views import registro_usuario, DeleteUserView, EditUserView

from . import views

app_name = 'users'
urlpatterns = [
    path('<int:pk>', EditUserView.as_view(), name='edit'),
    path('<int:pk>/delete', DeleteUserView.as_view(), name='delete')
]

src/rubrics/models.py
from django.db import models
import pandas as pd
import io

# Create your models here.

class Rubric(models.Model):
    name = models.TextField(max_length=50)
    table = models.TextField(max_length=2000)
    duration_min = models.FloatField()
    duration_max = models.FloatField()

    def to_df(self):
    	return pd.read_csv(io.StringIO(self.table), header=0, sep=',')

    def get_name(self):
    	return self.name

    def __str__(self):
    	return self.name

    def get_absolute_url(self):
        return reverse('rubric:view', kwargs={'rubrica_id': self.pk})

src/rubrics/forms.py
from django import forms
from .models import Rubric
import pandas as pd


class RubricEntryForm(forms.Form):
	'''
	Forma para una entrada de la rubrica, para la interfaz de edicion.
	'''
	text = forms.CharField(max_length=50, widget=forms.Textarea())
	col = forms.IntegerField()
	row = forms.IntegerField()

class RubricAchForm(forms.Form):
	'''
	Forma para una celda de puntaje de algún nivel de logro, para la interfaz de edicion.
	'''
	nlogro = forms.FloatField()
	col = forms.IntegerField()

class RubricNameForm(forms.Form):
	'''
	Forma para el nombre de la rúbrica.
	'''
	name = forms.CharField(max_length=50, required=True)

class RubricDurationForm(forms.Form):
	'''
	Forma para la duración de la evaluación, en minutos.
	'''
	duration_min = forms.DecimalField(max_digits=3)
	duration_max = forms.DecimalField(max_digits=3)

src/rubrics/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic.edit import DeleteView, CreateView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required, permission_required

from .models import Rubric
from evaluations.models import Evaluation
from .forms import RubricEntryForm, RubricAchForm, RubricNameForm, RubricDurationForm

import pandas as pd
import numpy as np


@login_required
def rubrics_page(request, *args):

	# TODO: Permitir ver solo si el usuario tiene el derecho
	rubric_ids = map(lambda x: x.get('id'), Rubric.objects.all().values('id'))
	rubric_names = map(lambda x: x.get('name'), Rubric.objects.all().values('name'))
	rubric_htmls = map(lambda x: x.to_df().to_html(index=False, classes="rubric_table", justify="left"), Rubric.objects.all())

	context = {
		"rubrics": zip(rubric_ids, rubric_names, rubric_htmls),
	}
	return render(request, "rubrics.html", context)

@login_required
@permission_required('rubrics.add_rubric')
def newRubricView(request):
	try:
		old_id = Rubric.objects.latest('id').id
	except ObjectDoesNotExist:
		old_id = 0
	new_id = old_id +  1
	rubrica = Rubric(id=new_id, name = "Rubrica {}".format(new_id),
				table="Criterio,6.0\nCriterio 1,nlogro1\n",
				duration_min=5., duration_max=10.)
	rubrica.save()
	return redirect("rubrics:view", rubric_id=new_id)

class RubricCopyView(PermissionRequiredMixin, LoginRequiredMixin, View):
	'''
	Vista responsable de crear una copia para la edición de una rúbrica asociada a una
	evaluación dada
	'''
	permission_required = 'rubrics.add_rubric'
	def post(self, request, rubric_id, eval_id):
		rubrica = get_object_or_404(Rubric, pk=rubric_id)
		name = "Rubrica {} de evaluacion {}".format(rubric_id, eval_id)
		# Si ya hice esto antes, solo ver la rubrica
		print(name, rubrica.name)
		if name==rubrica.name:
			return redirect("rubrics:view", rubric_id=rubric_id)
		# Crear una copia con el nombre nuevo
		rubrica_new = Rubric(name = name,
					table=rubrica.table,
					duration_min=rubrica.duration_min, duration_max=rubrica.duration_max)
		rubrica_new.save()
		# Reasignar la rubrica de esta evaluación a la neuva rubrica
		Evaluation.objects.filter(pk=eval_id).update(rubric=rubrica_new)

		return redirect("rubrics:view", rubric_id=rubrica_new.id)

class RubricView(LoginRequiredMixin, View):

	def get(self, request, rubric_id):
		rubrica = get_object_or_404(Rubric, pk=rubric_id)
		rubrica_df = rubrica.to_df()
		name_form = RubricNameForm({'name' : rubrica.get_name()})
		time_form = RubricDurationForm(
			{'duration_min' : rubrica.duration_min,
			'duration_max' : rubrica.duration_max})

		nlogro_forms = []
		for index, points in enumerate(rubrica_df.columns.values):
			if index!=0: nlogro_forms.append(RubricAchForm({'col' : index, 'nlogro' : points}))

		rows_forms = []
		for row_index, row_forms in rubrica_df.iterrows():
			row = []
			for col_index, entry in enumerate(row_forms):
				row.append(RubricEntryForm({'row' : row_index, 'col' : col_index, 'text' :entry}))
			rows_forms.append(row)

		context = {	'rows_forms' : rows_forms,
					'nlogro_forms': nlogro_forms,
					'name_form' : name_form,
					'time_form' : time_form,
					'rubrica_id' : rubric_id,
					'duration_min' : rubrica.duration_min,
					'duration_max' : rubrica.duration_max}

		if request.user.has_perm('rubrics.change_rubric'):
			return render(request, 'rubrics/rubric_editor.html', context)
			
		# TODO: Permitir ver solo si el usuario tiene el derecho
		return render(request, 'rubrics/rubric_view.html', context)

	def post(self, request, rubric_id):
		if not request.user.has_perm('rubrics.edit_rubric'):
			return HttpResponseForbidden()
		nlogros = np.array(request.POST.getlist('nlogro'))
		data = np.array(request.POST.getlist('text'))

		cols = np.append(['Criterio'], nlogros)

		ncols = cols.size
		nrows = int(data.size/ncols)
		rows = [data[ncols*i:ncols*(i+1)] for i in range(0, nrows)]

		name_form = RubricNameForm(request.POST)
		time_form = RubricDurationForm(request.POST)

		if name_form.is_valid() and time_form.is_valid():
			new_name = name_form.cleaned_data['name']
			dmin = time_form.cleaned_data['duration_min']
			dmax = time_form.cleaned_data['duration_max']
			df = pd.DataFrame(rows, columns=cols)
			df_csv = df.to_csv(None, sep=',', index=False)

			Rubric.objects.filter(pk=rubric_id).update(table=df_csv)
			Rubric.objects.filter(pk=rubric_id).update(name=new_name)
			Rubric.objects.filter(pk=rubric_id).update(duration_min=dmin, duration_max=dmax)


		return HttpResponseRedirect("")



class DeleteRubricView(PermissionRequiredMixin, SuccessMessageMixin, DeleteView):
	model = Rubric
	success_url = reverse_lazy('Rubrics Page')
	success_message = "Rubrica Borrada"
	permission_required = 'rubrics.del_rubric'

src/rubrics/templates/rubrics.html
{% extends 'base.html' %}

{% load static %}

{% block title %}

<title>
  Sistema de Evaluación: Rúbricas
</title>

{% endblock title %}

{% block stylesheets %}

<!-- Rubrics CSS -->
<link rel="stylesheet" href={% static 'rubrics/rubrics.css' %}>

{% endblock stylesheets %}

{% block javascript %}

<!-- Rubrics JS -->
<script src={% static 'rubrics/rubrics.js' %}></script>

{% endblock javascript %}

{% block content %}

<!-- Portada -->
<div class="w3-container" id="portada" style="margin-top:80px; margin-bottom:10px">
  <h1 class="w3-xxxlarge w3-text-red"><b>Rúbricas</b></h1>
  <hr style="width:50px;border:5px solid red" class="w3-round">
</div>

<div class="w3-container">
  <form action="{% url 'rubrics:new' %}" method="POST">
    {% csrf_token %}
    <button class="w3-button w3-large w3-green w3-right w3-round">
      Agregar nueva rúbrica
    </button>
  </form>
  <br>
</div>

<!-- Rubrics Dynamic List -->
{% for id, name, html in rubrics %}

<button onclick="detailToggle('info_{{ id }}')" class="w3-btn w3-red w3-block w3-margin w3-round" style="width: 75%">
  <h3>
    {{ name }}
  </h3>
</button>

<div id="info_{{ id }}" class="w3-hide w3-container w3-pale-red w3-center w3-padding-large w3-margin" style="width: 75%">
  <div class="w3-container">
    {{ html|safe }}
  </div>
  <div class="w3-container">
    <form action="{% url 'rubrics:view' id %}" method="GET">
      {% csrf_token %}
      <button class="w3-button w3-large w3-margin-right w3-green w3-left w3-round">
        Editar
      </button>
    </form>
    <button onClick="deleteDialogToggle('dialog_{{ id }}')" class="w3-button w3-large w3-red w3-right w3-round">
      Eliminar
    </button>

    <!-- The Modal -->
    <div id="dialog_{{ id }}" class="w3-modal">
      <div class="w3-modal-content w3-round">
        <header class="w3-container w3-red">
          <h3>
            ¿Estas seguro de querer borrar esta rubrica?
          </h3>
        </header>
        <div class="w3-container">
          <p>
            Esta acción no se puede deshacer!
          </p>
        </div>
        <footer class="w3-container">
          <form id="form_{{ id }}" action="{% url 'rubrics:delete' pk=id %}" method="POST">
            {% csrf_token %}
            <button class="w3-button w3-large w3-margin-right w3-red w3-left w3-round">
              Confirmar
            </button>
          </form>
          <button onClick="deleteDialogToggle('dialog_{{ id }}')" class="w3-button w3-large w3-green w3-right w3-round w3-closebtn">
            Cancelar
          </button>
        </footer>
      </div>
    </div>

  </div>
</div>

{% endfor %}

{% endblock content %}