src/evaluaciones/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

src/project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views

from users.views import landing_page, evaluators_page, registro_usuario
from courses.views import courses_page
from evaluations.views import evaluations_page
from rubrics.views import rubrics_page

urlpatterns = [
    path('', landing_page, name="Landing Page"),
    path('cursos/', courses_page, name="Courses Page"),
    #path('evaluadores/', evaluators_page, name="Evaluators Page"),
    path('evaluadores/', registro_usuario.as_view(), name="Evaluators Page"),
    path('evaluadores/', include('users.urls'), name="Edit Users"),
    path('rubricas/', rubrics_page, name="Rubrics Page"),
    path('rubricas/', include('rubrics.urls'), name="Rubrics Editor"),
    path('evaluaciones/', evaluations_page, name="Evaluations Page"),
    path('evaluaciones/', include('presentations.urls'), name="Evaluation Form"),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('admin/', admin.site.urls),
]

src/users/urls.py
from django.urls import path
from .views import registro_usuario, DeleteUserView, EditUserView

from . import views

app_name = 'users'
urlpatterns = [
    path('<int:pk>', EditUserView.as_view(), name='edit'),
    path('<int:pk>/delete', DeleteUserView.as_view(), name='delete')
]

src/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class BaseUser(AbstractUser):
    
    def __str__(self):

        return self.get_username()

src/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import BaseUser

# Create your forms here.

class BaseUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = BaseUser
        fields = ['first_name', 'last_name', 'email', 'username']
        labels = {
            'first_name': 'nombre',
            'last_name': 'apellido',
            'email': 'email',
            'username': 'username'
        }

class BaseUserChangeForm(UserChangeForm):

    class Meta:
        model = BaseUser
        fields = ('username', 'email')

src/users/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
from .forms import BaseUserCreationForm
from django.views.generic import CreateView, DeleteView, UpdateView
from .models import BaseUser
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy, reverse

def landing_page(request, *args):

    return render(request, 'landing_page.html')

def evaluators_page(request, *args):
    form = BaseUserCreationForm
    return render(request, 'evaluators.html', {'form':form})

class registro_usuario(CreateView):
    model = BaseUser 
    template_name = 'evaluators.html'
    form_class = BaseUserCreationForm

    def get_context_data(self, **kwargs):
        ctx = super(registro_usuario,self).get_context_data(**kwargs)
        queryset1 = BaseUser.objects.filter(is_staff=False)
        queryset2=[]
        for user in queryset1:
            queryset2.append(user.id)
        ctx["evaluators"] = zip(queryset1, queryset2)
	
        return ctx

    def form_valid(self, form):
        form.save()
        messages.success(self.request, "Usuario creado con exito, su contraseña es: "+form['password1'].value())
        return render(self.request, 'evaluators.html', self.get_context_data())
    

class DeleteUserView(SuccessMessageMixin, DeleteView):
	model = BaseUser
	success_url = reverse_lazy('Evaluators Page')
	success_message = "deleted..."

class EditUserView(SuccessMessageMixin,UpdateView):
    model = BaseUser
    fields = ['first_name', 'last_name', 'email', 'username']
    success_url = reverse_lazy('Evaluators Page')
    success_message = "Usuario modificado"

src/users/templates/evaluators.html
{% extends 'base.html' %}

{% load static %}

{% block title %}

  <title>
    Sistema de Evaluación: Evaluadores
  </title>

{% endblock title %}

{% block stylesheets %}

  <!-- Evaluators CSS -->
  <link rel="stylesheet" href={% static 'users/evaluators.css' %}>

{% endblock stylesheets %}

{% block javascript %}

  <!-- Evaluators JS -->
  <script src={% static 'users/evaluators.js' %}></script>

{% endblock javascript %}

{% block content %}

  <!-- Title -->
  <div class="w3-container evaluators-welcome-message-container" id="portada">
    <h1 class="w3-xxxlarge w3-text-red">
      <b>
        Evaluadores
      </b>
    </h1>
    <hr class="w3-round base-horizontal-rule">
    <p>
      <h3>
        Seleccione un evaluador
      </p>
    </h2>
  </div>
  {% for message in messages %}
  <li class="{{ message.tags }}">{{ message }}</li>
  {% endfor %}
  <!--Cajas evaluadores-->
  <div class="w3-row-padding w3-center w3-margin-top">
      {%for evaluator,id in evaluators%}
      
    <div class="w3-quarter w3-margin-top">
      <button onclick="document.getElementById('info_{{id}}').style.display='block'" class="w3-card w3-container w3-hover-shadow evaluators-evaluator-card">
        <h3>
          {{evaluator.first_name}} {{evaluator.last_name}}
        </h3>
        <br>
        <i class="fas fa-user-alt evaluators-evaluator-icon"></i>
        <p>
          {{evaluator.email}}
      </button>
    </div>

    <div id="info_{{id}}" class="w3-modal">
      <div class="w3-modal-content w3-card-4 w3-animate-zoom evaluators-evaluator-modal">
        <div class="w3-center">
          <br>
          <span onclick="document.getElementById('info_{{id}}').style.display='none'" class="w3-button w3-xlarge w3-transparent w3-display-topright" title="Close Modal">
            ×
          </span>
          <div class="w3-margin">
            <button onclick="document.getElementById('edit_{{id}}').style.display='block'" class="w3-button w3-red w3-section w3-padding:10px" type="submit">
              Modificar
            </button>
            <br>
            <form id="form_{{ id }}" action="{% url 'users:delete' pk=id %}" method="POST">
                {% csrf_token %}
            <button class="w3-button w3-red w3-section w3-padding:10px" type="submit">
              Eliminar
            </button>
            </form>
          </div>
        </div>
      </div>
    </div>

    
     <div id="edit_{{id}}" class="w3-modal">
        <form method="POST" id="form_{{ id }}" action="{% url 'users:edit' pk=id %}">
            {%csrf_token%}
       <div class="w3-modal-content w3-card-4 w3-animate-zoom evaluators-add-modal">
         <div class="w3-center">
             <br>
             <span onclick="document.getElementById('edit_{{id}}').style.display='none'" class="w3-button w3-xlarge w3-transparent w3-display-topright" title="Close Modal">
               ×
             </span>
             <form class="w3-container" action="/action_page.php">
               <div class="w3-section">
                   <label>
                       <b>
                         Nombre
                       </b>
                     </label>
                     <input class="w3-input w3-border w3-margin-bottom form-control" type="text" value={{evaluator.first_name}} name="first_name" id="fn2" required>
                     <label>
                       <b>
                         Apellido
                       </b>
                     </label>
                     <input class="w3-input w3-border form-control" type="text" value={{evaluator.last_name}} name="last_name" id="ln2" required>
                     <label>
                         <b>
                           Correo
                         </b>
                       </label>
                     <input class="w3-input w3-border form-control" type="email" value={{evaluator.email}} name="email" id="email_{{id}}" required>
                     <input type="hidden" type="text" name="username" id="usrnm_{{id}}">
                     <button onclick="edit_User({{id}})" class="w3-button w3-block w3-red w3-section w3-padding" type="submit">
                         Editar
                     </button>
               </div>
             </form>
         </div>
       </div>
      </form>
     </div>
     
   {%endfor%}
    <!--Caja de agregar-->
    <div class="w3-quarter w3-margin-top">
      <button onclick="document.getElementById('agregar').style.display='block'" class="w3-card w3-container w3-light-gray w3-hover-shadow evaluators-add-card">
        <h3>
          Agregar evaluador nuevo
        </h3>
        <br>
        <i class="fas fa-user-plus evaluators-add-icon"></i>
      </button>
    </div>
    


    <form method="POST">
    {%csrf_token%}
    <div id="agregar" class="w3-modal">
      <div class="w3-modal-content w3-card-4 w3-animate-zoom evaluators-add-modal">
        <div class="w3-center">
          <br>
          <span onclick="document.getElementById('agregar').style.display='none'" class="w3-button w3-xlarge w3-transparent w3-display-topright" title="Close Modal">
            ×
          </span>
          <form class="w3-container" action="/action_page.php">
            <div class="w3-section">
              <label>
                <b>
                  Nombre
                </b>
              </label>
              <input class="w3-input w3-border w3-margin-bottom form-control" type="text" placeholder="Ingrese nombre" name="first_name" id="fn" required>
              <label>
                <b>
                  Apellido
                </b>
              </label>
              <input class="w3-input w3-border form-control" type="text" placeholder="Ingrese apellido" name="last_name" id="ln" required>
              <label>
                <b>
                  Correo
                </b>
              </label>
              <input class="w3-input w3-border form-control" type="email" placeholder="Ingrese correo" name="email" id="email" required>
              <input type="hidden" type="text" name="password1" id="pss1">
              <input type="hidden" type="text" name="password2" id="pss2">
              <input type="hidden" type="text" name="username" id="usrnm">
              <button onclick="create_User()" class="w3-button w3-block w3-red w3-section w3-padding" type="submit">
                Agregar
              </button>
            </div>
          </form>
        </div>
      </div>
    </form>
      <!--cierre de cajas de cursos-->
  </div>
</div>
  

  <script>
    function create_User() {
    var randomstring = Math.random().toString(36).slice(-8);
    document.getElementById("pss1").value=randomstring;
    document.getElementById("pss2").value=randomstring;
    document.getElementById("usrnm").value = document.getElementById("email").value;
  }

function edit_User(id) {
    document.getElementById("usrnm_"+id.toString()).value = document.getElementById("email_"+id.toString()).value;
  }
  </script>
{% endblock content %}

src/users/templates/landing_page.html
{% extends 'base.html' %}

{% load static %}

{% block title %}

	<title>
		Sistema de Evaluación: Bienvenida
	</title>

{% endblock title %}

{% block stylesheets %}

	<!-- Landing Page CSS -->
	<link rel="stylesheet" href={% static 'users/landing_page.css' %}>

{% endblock stylesheets %}

{% block javascript %}

	<!-- Landing Page JS -->
	<script src={% static 'users/landing_page.js' %}></script>

{% endblock javascript %}

{% block content %}
	<!-- Portada-->
	<div class="w3-container landing-welcome-message-container" id="portada">
		<h1 class="w3-xxxlarge w3-text-red">
			<b>
				Bienvenido al sistema de evaluación
			</b>
		</h1>
		<hr class="w3-round base-horizontal-rule">
		<p>
			<h3>
				Seleccione alguna sección para comenzar
			</p>
		</h2>
		<i class="far fa-arrow-alt-circle-left landing-welcome-arrow"></i>
	</div>

{% endblock content %}

src/users/templates/login.html
{% extends 'base.html' %}

{% load static %}


{% block title %}
	<title>
		Login
	</title>
{% endblock title %}

{% block stylesheets %}

	<!-- Login Page CSS -->
	<link rel="stylesheet" href={% static 'users/login_page.css' %}>

{% endblock stylesheets %}

{% block content %}
<div class="w3-container landing-welcome-message-container login-form">
  <form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Login</button>
  </form>
</div>
{% endblock content %}

src/users/templates/logout.html
{% extends 'base.html' %}

{% load static %}

{% block stylesheets %}

	<!-- Landing Page CSS -->
	<link rel="stylesheet" href={% static 'users/logout_page.css' %}>

{% endblock stylesheets %}

{% block content %}

<div class="w3-container landing-welcome-message-container logout-message">
		<h1 class="w3-xxxlarge w3-text-red">
			<b>
                You have been logged out
			</b>
		</h1>
</div>

{% endblock content %}