src/evaluaciones/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

src/presentations/urls.py
from django.urls import path

from .views import evaluation_form_page, update_context_view, upload_grade

app_name = 'presentations'
urlpatterns = [
    path('evaluar/<int:evaluation_id>/<int:group_id>', evaluation_form_page, name='form'),
    path('evaluar/<int:evaluation_id>/<int:group_id>/subir_nota', upload_grade, name='upload_grade'),
    path('evaluar/<int:evaluation_id>/<int:group_id>/update_context', update_context_view, name='ajax_update'),
]

src/project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views

from users.views import landing_page, evaluators_page, registro_usuario
from courses.views import courses_page
from evaluations.views import evaluations_page
from rubrics.views import rubrics_page

urlpatterns = [
    path('', landing_page, name="Landing Page"),
    path('cursos/', courses_page, name="Courses Page"),
    #path('evaluadores/', evaluators_page, name="Evaluators Page"),
    path('evaluadores/', registro_usuario.as_view(), name="Evaluators Page"),
    path('evaluadores/', include('users.urls'), name="Edit Users"),
    path('rubricas/', rubrics_page, name="Rubrics Page"),
    path('rubricas/', include('rubrics.urls'), name="Rubrics Editor"),
    path('evaluaciones/', evaluations_page, name="Evaluations Page"),
    path('evaluaciones/', include('presentations.urls'), name="Evaluation Form"),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('admin/', admin.site.urls),
]

src/rubrics/urls.py
from django.urls import path
from .views import RubricView, newRubricView, DeleteRubricView, RubricCopyView

from . import views

app_name = 'rubrics'
urlpatterns = [
    path('new', newRubricView, name='new'),
    path('<int:rubric_id>', RubricView.as_view(), name='view'),
    path('<int:pk>/delete', DeleteRubricView.as_view(), name='delete'),
    path('<int:rubric_id>/<int:eval_id>/copy', RubricCopyView.as_view(), name='copy')
]

src/users/urls.py
from django.urls import path
from .views import registro_usuario, DeleteUserView, EditUserView

from . import views

app_name = 'users'
urlpatterns = [
    path('<int:pk>', EditUserView.as_view(), name='edit'),
    path('<int:pk>/delete', DeleteUserView.as_view(), name='delete')
]

src/evaluations/models.py
from django.db import models

# Create your models here.

class Evaluation(models.Model):

    rubric = models.ForeignKey("rubrics.Rubric", null=True, on_delete=models.SET_NULL)
    course = models.ForeignKey("courses.Course", null=False, on_delete=models.CASCADE)
    default_allowed_evaluators = models.ManyToManyField("users.BaseUser")
    is_open = models.BooleanField(default=True)

src/evaluations/forms.py
from django import forms
from .models import Evaluation

class EvaluationsForm(forms.ModelForm):

    class Meta:
        model = Evaluation
        fields = [
            "course",
            "rubric"
        ]        

src/evaluations/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpRequest
from presentations.models import Grade
from .models import Evaluation
from courses.models import Course
from rubrics.models import Rubric
from presentations.models import Presentation
from django.db.models.query import QuerySet
from .forms import EvaluationsForm

from django.views import View

# Create your views here.


def evaluations_page(request: HttpRequest, *args):
    
    if request.user.is_staff:
        evaluaciones=  Evaluation.objects.all()
        if(request.method == "POST"):
            form = EvaluationsForm(request.POST)
            if form.is_valid():
                post = form.save(commit=True)
                post.save()
                course: Course = Evaluation.objects.get(id=post.id).course
                for group in course.group_set.all():
                    Presentation.objects.create(evaluation=Evaluation.objects.get(id=post.id), group=group)
            
        else:
            form = EvaluationsForm()
        return render(request, "evaluations.html",{'evaluaciones': evaluaciones, 'form' : form})
    else:
        userid = request.user.id  
        grades = Grade.objects.filter(evaluator_id = userid)[:10] #All grades for the evaluator     
        context = {
            'obj' : grades
        }
        return render(request, "evaluations.html", context)

src/evaluations/templates/evaluation_form.html
{% extends 'base.html' %}

{% load static %}

{% block title %}

<title>
  Sistema de Evaluación
</title>

{% endblock title %}

{% block stylesheets %}

<!-- Evaluation Form CSS -->
<link rel="stylesheet" href={% static 'evaluations/evaluations_form.css' %}>

{% endblock stylesheets %}

{% block javascript %}

<!-- Evaluation Form JS -->
<script src={% static 'evaluations/evaluations_form.js' %}></script>

{% endblock javascript %}

{% block content %}

<!-- Photo grid (modal) -->

<!-- Portada -->
<div class="w3-container" id="portada" style="margin-top:80px; margin-bottom:10px">
  <h1 class="w3-xxxlarge w3-text-red">
    <b>
      Evaluación
      <i class="w3-text-green">
        en curso
      </i>
    </b>
  </h1>
  <hr style="width:50px;border:5px solid red" class="w3-round">
</div>

<!-- Evaluacion -->
<div class="w3-container w3-center">
  <p><b>Lambda-Ideas</b> Presentación Tarea 2 <i>CC4401-1/Otoño/2019</i></p>
  <br>

  <div class="w3-panel  w3-margin-bottom">
    <ul class="w3-ul w3-light-grey w3-center w3-card-4">
      <li class="w3-dark-grey w3-xlarge w3-padding-32">Evaluadores <i class="fas fa-user-tie"></i> </li>
      <li class="w3-padding-16"> Evaluador 1 <i style="margin-left: 10px" class="w3-large fas fa-times"></i>
      </li>
      <li class=" w3-padding-16 presentado"> Evaluador 2 <i style="margin-left: 10px" class="far fa-check-circle"></i>
      </li>
      <li class="w3-padding-16"> Evaluador 3 <i style="margin-left: 10px" class="w3-large fas fa-times"></i></li>
      <li class="opcion w3-padding-16"> Agregar otro <i style="margin-left: 10px" class="fas fa-user-plus"></i>
      </li>
    </ul>
  </div>

  <div class="w3-row-padding" style="margin-top:30px">
    <div class="w3-half w3-margin-bottom ">
      <ul class="w3-ul w3-light-grey w3-center w3-card-4">
        <li class="w3-dark-grey w3-xlarge w3-padding-32">Miembros del equipo <i class="fas fa-user-friends"></i></li>
        <li class="presentado w3-padding-16">Pablo Aliaga <i class="far fa-check-circle"></i> <i class="w3-small">ya presentó</i></li>
        <li class="w3-padding-16">Bastián Matamala</li>
        <li class="presentado w3-padding-16">Camila Quilape <i class="far fa-check-circle"></i><i class="w3-small">ya presentó</i></li>
        <li class=" w3-padding-16">Andrea Park</li>
      </ul>
    </div>

    <div class="w3-half w3-margin-bottom ">
      <ul class="w3-ul w3-light-grey w3-center w3-card-4">
        <li class="w3-dark-grey w3-xlarge w3-padding-32">Miembros que presentan <i class="fas fa-chalkboard-teacher"></i></li>
        <li class="w3-padding-16">Andrea Park <i style="margin-left: 10px" class="w3-large fas fa-times"></i></li>
        <li class=" opcion w3-padding-16" id="mas"> Agregar otro <i style="margin-left: 10px" class="fas fa-user-plus"></i></li>

      </ul>
    </div>
  </div>

  <p>Seleccione el nivel de logro alcanzado por el grupo en cada ámbito</p>
</div>

<div class="w3-panel  w3-margin-bottom">
  <ul class="w3-ul w3-light-grey w3-center w3-card-4">
    <li class="w3-red w3-xlarge w3-padding-32">Contenidos <i class="far fa-check-circle"></i></li>
    <li class="opcion w3-padding-16"> No incluye las interfaces
      solicitadas
    </li>
    <li class="opcion w3-padding-16 selected"> Faltan la mayoria de las
      interfaces
    </li>
    <li class="opcion w3-padding-16"> Solo faltan 1 o 2 interfaces </li>
    <li class="opcion w3-padding-16"> Incluye todas las interfaces
      solicitadas
    </li>
  </ul>
</div>




<div class="w3-panel w3-margin-bottom">
  <ul class="w3-ul w3-light-grey w3-center w3-card-4">
    <li class="w3-orange w3-xlarge w3-padding-32">Calidad del material
      <i class="fas fa-exclamation-circle"></i><i class="w3-medium"> falta seleccionar</i></li>
    <li class="opcion w3-padding-16">Presentación con muchos
      errores ortográficos, todas
      las imágenes son de baja
      resolución
    </li>
    <li class="opcion w3-padding-16">Algunos errores
      ortográficos, casi todas las
      imágenes son de baja
      resolución
    </li>
    <li class="opcion w3-padding-16">Pocos errores ortográficos,solo algunas imágenes sonde baja resolución
    </li>
    <li class="opcion w3-padding-16">Pocos errores ortográficos,
      todas las imágenes son de
      buena resolución
    </li>
  </ul>
</div>

<div class="w3-panel w3-margin-bottom">
  <ul class="w3-ul w3-light-grey w3-center w3-card-4">
    <li class="w3-red w3-xlarge w3-padding-32">Relación con requisitos
      funcionales <i class="far fa-check-circle"></i>

    </li>
    <li class="opcion w3-padding-16">Solo describe las
      interfaces, sin mencionar
      requisito alguno

    </li>
    <li class="opcion w3-padding-16">Solo para algunas de las
      interfaces explica cómo
      satisfacen los requisitos
      funcionales

    </li>
    <li class="opcion w3-padding-16 selected">Para casi todas las
      interfaces, explica cómo
      satisfacen los requisitos
      funcionales
    </li>
    <li class="opcion w3-padding-16">Explica claramente como
      cada interfaz satisface los
      requisitos funcionales

    </li>
  </ul>
</div>

<div class="w3-panel w3-margin-bottom">
  <ul class="w3-ul w3-light-grey w3-center w3-card-4">
    <li class="w3-red w3-xlarge w3-padding-32">Organización de la
      información <i class="far fa-check-circle"></i>

    </li>
    <li class="opcion w3-padding-16">No se entiende la
      presentación porque no haysecuencia lógica de
      información
    </li>
    <li class="opcion w3-padding-16">Es difícil seguir la
      presentación, porque el
      presentador “salta” entre
      diapositivas

    </li>
    <li class="opcion w3-padding-16">La información está
      presentada en una
      secuencia lógica

    </li>
    <li class="opcion w3-padding-16 selected">La información es
      presentada en una forma
      lógica e interesante

    </li>
  </ul>
</div>

<div class="w3-panel w3-margin-bottom">
  <ul class="w3-ul w3-light-grey w3-center w3-card-4">
    <li class="w3-red w3-xlarge w3-padding-32">Forma <i class="far fa-check-circle"></i>

    </li>
    <li class="opcion w3-padding-16">No se entiende lo que dice(en términos fonéticos y
      cinéticos)

    </li>
    <li class="opcion w3-padding-16">Se entiende lo que dice la
      de manera parcial (su
      cuerpo no acompaña sus
      palabras)

    </li>
    <li class="opcion w3-padding-16 selected">Se da a entender,
      presentando de manera
      eficiente y adecuado
      lenguaje corporal

    </li>
    <li class="opcion w3-padding-16">Se da a entender siempre,
      destacando en su forma
      (pausas, dicción, contacto
      visual, gesticulación, otros)

    </li>
  </ul>
</div>

<div class="w3-panel w3-margin-bottom">
  <ul class="w3-ul w3-light-grey w3-center w3-card-4">
    <li class="w3-red w3-xlarge w3-padding-32">Entusiasmo <i class="far fa-check-circle"></i>

    </li>
    <li class="opcion w3-padding-16">No muestra interés en su
      entrega

    </li>
    <li class="opcion w3-padding-16">Se muestra algo negativo
      acerca de su entrega

    </li>
    <li class="opcion w3-padding-16 selected">Ocasionalmente habla en
      forma positiva

    </li>
    <li class="opcion w3-padding-16">Habla en forma positiva
      durante casi toda la
      presentación
    </li>
  </ul>
</div>

<div class="w3-panel w3-margin-bottom w3-card-4 w3-padding-16 w3-half w3-right" style="margin-right: 1.8%">
  <span style="margin-left:21%"><i class="far fa-clock"></i> Hora final
    <input class="w3-input w3-border w3-round" type="number" size="1" placeholder="15" style="width:15%; display:inline; margin-left: 10px"> : <input class="w3-input w3-border w3-round" style="width:15%; display:inline" type="number" placeholder="35"></span>
</div>

<div class="w3-panel w3-right w3-half">
  <button class="w3-button w3-xlarge w3-red" style="margin-left: 15%"> <i class="fas fa-envelope-open-text"></i> Entregar evaluación</button>
</div>

{% endblock content %}

src/evaluations/templates/evaluations.html
{% extends 'base.html' %}

{% load static %}

{% block title %}

  <title>
    Sistema de Evaluación: Evaluaciones
  </title>

{% endblock title %}

{% block stylesheets %}

  <!-- Evaluations CSS -->
  <link rel="stylesheet" href={% static 'evaluations/evaluations.css' %}>

{% endblock stylesheets %}

{% block javascript %}

  <!-- Evaluations JS -->
  <script src={% static 'evaluations/evaluations.js' %}></script>

{% endblock javascript %}

{% block content %}
  
  <!-- Portada -->
  <div class="w3-container" id="portada" style="margin-top:80px; margin-bottom:10px">
    <h1 class="w3-xxxlarge w3-text-red">
      <b>
        Evaluaciones
      </b>
    </h1>
    <hr style="width:50px;border:5px solid red" class="w3-round">
  </div>

  {% if user.is_staff %}
  <div class="w3-container">
      <button onclick="document.getElementById('agregar').style.display='block'" class="w3-button w3-large w3-green w3-right w3-round">
        Agregar nueva evaluación
      </button>
    <br>
  </div>

  <!-- Caja para agregar evaluaciones -->
  <form method="POST">
    {%csrf_token%}
    <div id="agregar" class="w3-modal">
      <div class="w3-modal-content w3-card-4 w3-animate-zoom evaluators-add-modal">
        <div class="w3-center">
          <br>
          <span onclick="document.getElementById('agregar').style.display='none'" class="w3-button w3-xlarge w3-transparent w3-display-topright" title="Close Modal">
            ×
          </span>
          <form class="w3-container" action="/action_page.php">
            <div class="w3-section">
              {{ form }}
              <button onclick="" class="w3-button w3-block w3-red w3-section w3-padding" type="submit">
                Agregar
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </form>

  {% endif %}
  <!--Seccion  evaluaciones-->
  {% if not user.is_staff %}
    <!-- Para evaluadores -->
    {% regroup obj by presentation.evaluation as evaluation_list %}
    {% for evaluation in evaluation_list %}
      {% if not forloop.counter > 10 %}
      <button onclick="myFunction({{ evaluation.grouper.id }})" class="w3-btn w3-red w3-block w3-margin" style="width: 75%">
        <h3>
          {{ evaluation.grouper.course.code }} | {{ evaluation.grouper.id }}
        </h3>
      </button>

      <div id= {{ evaluation.grouper.id }} class="w3-hide w3-container w3-pale-red  w3-padding-large w3-margin"style="width: 75%">
        <table>
        {% for grade in evaluation.list %}
          <tr>
          <td>Grupo: {{ grade.presentation.group.name }}</td>
          {% if grade.state %}
            <td>Contestada </td>
            {% if evaluation.grouper.is_open %}
              <td><a href='/evaluaciones/evaluar/{{ evaluation.grouper.id }}/{{ grade.presentation.group.id }}' class="w3-bar-item w3-button w3-hover-white">Modificar</a></td>
            {% endif %}
            {% else %}
            <td>No contestada </td>
            {% if evaluation.grouper.is_open %}
              <td><a href='/evaluaciones/evaluar/{{ evaluation.grouper.id }}/{{ grade.presentation.group.id }}' class="w3-bar-item w3-button w3-hover-white">Contestar</a></td>
            {% endif %}
          {% endif %}
          </tr>
        {% endfor %}
        </table>
      </div>
      {% endif %}

    {% endfor %}
  {% else %}
  <!-- Para admin -->
    {% for eval in evaluaciones %}
      <button onclick="myFunction({{ eval.pk}})" class="w3-btn w3-red w3-block w3-margin" style="width: 75%"><h3>
        Evaluación {{ eval.pk}}</h3></button>

      <div id={{eval.pk}} class="w3-hide w3-container w3-pale-red  w3-padding-large w3-margin"style="width: 75%">

        <p><li>Curso: {{eval.course.code}}</li>
            <li>Fecha inicio: -</li>
            <li>Fecha término: -</li>
            <li class="w3-padding-16"><form action="{% url 'rubrics:copy' rubric_id=eval.rubric.id eval_id=eval.id %}" method="POST">
              {% csrf_token %}
              Rúbrica asociada: <button class="w3-button w3-white w3-border w3-border-red w3-round-large">{{eval.rubric.name}}</button>
            </form></li>

        </p>

        <div class="w3-container">
          <form class="w3-third w3-left" action="{% url 'presentations:form'  evaluation_id=eval.id group_id=1 %}" method="GET">
            <button class="w3-button w3-large w3-red w3-margin-left w3-round">Empezar Evaluación</button>
          </form>
          <form class="w3-third w3-right" action="" method="POST"> 
          {% csrf_token %}
          <button class="w3-button w3-white w3-border w3-border-red w3-round-large">Exportar puntajes</button>
          </form>
        </div>

        <form class="w3-padding-16" action="" method="POST">
          <button class="w3-button w3-large w3-red w3-right w3-round">Eliminar</button>
        </form>
      </div>
  {% endfor %}
  {% endif %}

  

  

{% endblock content %}

src/evaluations/templates/select_criterion.html
<!-- Template para mostrar una selección de nivel de logro -->
{% with id=widget.attrs.id %}

<div class="w3-panel  w3-margin-bottom">
<ul {% if id %} id="{{ id }}"{% endif %} {% if widget.attrs.class %} class="{{ widget.attrs.class }} w3-ul w3-light-grey w3-center w3-card-4"{% endif %}>
	
	<li class="w3-red w3-xlarge w3-padding-32">{{widget.label}}<i class="far fa-check-circle"></i></li>

	{% for group, options, index in widget.optgroups %}
		{% if group %}<li >{{ group }}<ul{% if id %} id="{{ id }}_{{ index }}"{% endif %}>{% endif %}
		{% for option in options %}
	    	<li class="opcion w3-padding-16">{% include option.template_name with widget=option %}</li>
	    {% endfor %}
	    
	    {% if group %}</ul></li>{% endif %}
    {% endfor %}
</ul>{% endwith %}

src/evaluations/templates/select_criterion_option.html
<!-- html para mostrar un solo nivel de logro -->
{% if widget.wrap_label %}
<label{% if widget.attrs.id %} for="{{ widget.attrs.id }}"{% endif %}>
{% endif %}
<input type="{{ widget.type }}" name="{{ widget.name }}"
{% if widget.value != None %} value="{{ widget.value|stringformat:'s' }}"{% endif %}
{% include "django/forms/widgets/attrs.html" %}>
{% if widget.wrap_label %} {{ widget.label }}</label>{% endif %}